name: Build Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image Tag
        required: true
        default: latest

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    env:
      IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - uses: actions/checkout@v5

      - name: Lowercase image name
        run: echo "IMAGE=${IMAGE,,}" >> $GITHUB_ENV

      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Login GHCR
        run: |
          echo "${{ github.token }}" | \
          buildah login \
            -u "${{ github.actor }}" \
            --password-stdin \
            ghcr.io

      - name: Build
        run: |
          buildah build \
            --format oci \
            --layers \
            -f Containerfile \
            -t "$IMAGE:${{ inputs.tag }}" \
            .

      - name: Push tag
        run: |
          buildah push \
            "$IMAGE:${{ inputs.tag }}" \
            "docker://$IMAGE:${{ inputs.tag }}"

      - name: Tag latest
        if: inputs.tag != 'latest'
        run: |
          buildah tag \
            "$IMAGE:${{ inputs.tag }}" \
            "$IMAGE:latest"

      - name: Push latest
        if: inputs.tag != 'latest'
        run: |
          buildah push \
            "$IMAGE:latest" \
            "docker://$IMAGE:latest"

      - name: Tag SHA
        run: |
          buildah tag \
            "$IMAGE:${{ inputs.tag }}" \
            "$IMAGE:${{ github.sha }}"

      - name: Push SHA
        run: |
          buildah push \
            "$IMAGE:${{ github.sha }}" \
            "docker://$IMAGE:${{ github.sha }}
