name: Build Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image Tag
        default: latest
        required: true

      push:
        description: Push to GHCR
        type: boolean
        default: true

jobs:
  build:

    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/cachy-bootc

    steps:

      - uses: actions/checkout@v5

      - name: Lowercase image name
        run: |
          echo "IMAGE=${IMAGE,,}" >> $GITHUB_ENV

      - name: Install Buildah
        run: |
          sudo apt update
          sudo apt install -y buildah

      - name: Build Image
        run: |
          buildah build \
            --format oci \
            --layers \
            -t $IMAGE:${{ inputs.tag }} \
            .

      - name: Login GHCR
        if: inputs.push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          buildah login \
            -u ${{ github.actor }} \
            --password-stdin \
            ghcr.io

      - name: Push latest
        if: inputs.push
        run: |
          buildah push \
            $IMAGE:${{ inputs.tag }}

      - name: Tag SHA
        if: inputs.push
        run: |
          buildah tag \
            $IMAGE:${{ inputs.tag }} \
            $IMAGE:${{ github.sha }}

      - name: Push SHA
        if: inputs.push
        run: |
          buildah push \
            $IMAGE:${{ github.sha }}
